# Generated by Django 4.0.3 on 2022-03-23 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0008_alter_schedule_options_alter_teacher_options'),
        ('subject', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='class_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='teacher.classtype'),
            preserve_default=False,
        ),
    ]
