# Generated by Django 4.0.3 on 2022-03-17 03:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subject', '0001_initial'),
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='medium',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subject.teachingmedium'),
        ),
        migrations.DeleteModel(
            name='TeachingMedium',
        ),
    ]
