# Generated by Django 4.0.3 on 2022-03-22 08:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0002_alter_schedule_medium_delete_teachingmedium'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dayofweek',
            options={'verbose_name_plural': 'Day of Week'},
        ),
        migrations.AddField(
            model_name='teacher',
            name='profile_picture',
            field=models.FileField(null=True, upload_to='teacher/profilepicture'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='teacher.district'),
        ),
    ]
