# Generated by Django 4.0.3 on 2022-03-22 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0003_alter_dayofweek_options_teacher_profile_picture_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='profile_picture',
            field=models.FileField(blank=True, null=True, upload_to='teacher/profilepicture'),
        ),
    ]
