# Generated by Django 4.0.3 on 2022-03-22 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0005_alter_teacher_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='avg_rating',
            field=models.FloatField(default=0.0, max_length=2),
        ),
    ]
