# Generated by Django 4.0.3 on 2022-03-22 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0006_teacher_avg_rating'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teacher',
            options={'ordering': ('-avg_rating',)},
        ),
    ]
