# Generated by Django 4.0.3 on 2022-03-22 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0007_alter_teacher_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='schedule',
            options={'ordering': ('-teacher__avg_rating',)},
        ),
        migrations.AlterModelOptions(
            name='teacher',
            options={},
        ),
    ]
